### PR TITLE
Allow functions in authentication.apiRequest.headers

### LINKED ISSUE #71: Support for functions in `apiRequest` with option to use context returned in loginRequest
This is not possible right now:
```json
{
  "parameters": {
    "api": {
      "name": "yyy",
      "baseUrl": "https://XXX",
      "authentication": {
        "type": "login",
        "loginRequest": {
          "endpoint": "/v1/login",
          "headers": {
            "Content-Type": "application/json"
          },
          "method": "POST",
          "params": {
            "email": {
              "attr": "#email"
            },
            "password": {
              "attr": "#password"
            }
          }
        },
        "apiRequest": {
          "headers": {
            "Authorization": {
              "function": "concat",
              "args": [
                "Bearer ",
                {
                  "token": "token"
                }
              ]
            }
          }
        }
      }
    },
    "config": {
      "#email": "KBC::XXX",
      "#password": "KBC::XXX",
      "id": "yyy",
      "debug": "1",
      "jobs": [
        {
          "method": "GET",
          "endpoint": "/v1/list",
          "params": []
        }
      ]
    }
  }
}
```

Especially:
```json
"apiRequest": {
    "headers": {
        "Authorization": {
            "function": "concat",
            "args": [
                "Bearer ",
                {
                    "token": "token"
                }
            ]
        }
    }
}
```
We already support passing context from loginRequest, but it's not able to use this contect with function.

I think it's a valid case, since headers `Authentication: "Bearer abcdef0123456"` are very common.

### PR DESCRIPTION
**Pull request by ujovlado**
Fixes #71

### CODE REVIEW

**Comment by ujovlado** [comment]
I will wait until https://github.com/keboola/generic-extractor/tree/cleanup is merged

**Comment by ujovlado** [comment]
@odinuv mozeme potom pokracovat tu, je to rebasnute

**Comment by ujovlado** [comment]
@odinuv sa to tam nejako "premergovalo", nie? (mozem to potom este na konci fixnut)

**Comment by odinuv** [comment]
@ujovlado co se permergovalo?

**Comment by odinuv** [comment]
ready to merge, but update docs first

**Pull request merged**
